#!/usr/bin/env python3
"""Choose the day-ahead planner's two parameters on Jul 2-Aug 31 2023 only.

September 2023 (the evaluation month) and the 2026 days are never touched here. Each
candidate is scored the way the 30-day headline is: one continuous run over every
selection day per zone (the battery carries its charge from day to day), averaged over
the four zones and divided by the number of days.
Writes docs/PARAMS.md.  Run:  python3 scripts/select_params.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from wattgap import econ  # noqa: E402
from wattgap.data import EVALUATION, SELECTION, ZONES, days_between  # noqa: E402

GRID = [econ.PlannerParams(h, m) for h in (1, 2, 3, 4, 6) for m in (None, 1.0, 1.25, 1.5, 2.0, 3.0)]


def score(policy: econ.Policy, days) -> float:
    return sum(econ.simulate("", z, days, policy=policy).net for z in ZONES) / len(ZONES) / len(days)


def main() -> None:
    days = days_between(*SELECTION)
    fair = score(econ.POLICIES["scheduled"], days)
    rows = sorted(((score(econ.planned(p), days), p) for p in GRID), key=lambda r: -r[0])
    best = rows[0][1]
    lines = [
        "# Planner parameter selection",
        "",
        f"Generated by `python3 scripts/select_params.py`. Selection days: {SELECTION[0]} to {SELECTION[1]} "
        f"({len(days)} real days, four load zones). Evaluation days ({EVALUATION[0]} to {EVALUATION[1]}) "
        "and the 2026 days were **not** used.",
        "",
        "Score: net $ per home per day from one continuous run over the selection days (charge carries over),",
        f"averaged over the four zones. The charge window is not a parameter: it is the {econ.refill_hours(econ.SPEC)} cheapest DAM hours,",
        "the time a full-power refill from the reserve takes.",
        f"Fair schedule on the same days: **${fair:.3f}/home/day**.",
        "",
        "| window_h (discharge) | spike_mult | $/home/day | vs fair |",
        "|---:|---:|---:|---:|",
        *[f"| {p.window_h} | {p.spike_mult or 'off'} | {v:.3f} | {v - fair:+.3f} |" for v, p in rows],
        "",
        f"**Chosen:** window_h={best.window_h}, spike_mult={best.spike_mult} (the top row).",
        "",
        "Disclosure: the first grid had spike_mult in {off, 1.5, 2, 3}. Its best value sat at the edge (1.5), so the",
        "grid was widened once to add 1.0 and 1.25. That second look also used only the selection days.",
        "",
        "Disclosure: the first planner version used the same number of hours for charging and discharging, and it scored",
        "candidates on independent days that each started at 50% charge. When we ran September we saw a 1-hour charge",
        "window couldn't refill the battery from one day to the next. So we sized the charge window by physics",
        "(refill time) and switched to continuous scoring. That design change came from looking at the evaluation",
        "month, but no parameter value was chosen on it.",
    ]
    out = Path(__file__).resolve().parents[1] / "docs" / "PARAMS.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    if best != econ.PLANNER:
        print(f"\nNOTE: econ.PLANNER is {econ.PLANNER}; set it to {best}")


if __name__ == "__main__":
    main()
